name: selenium_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - selenium
  - pandas
  - beautifulsoup4
  - requests
  - jupyter
  - ipykernel
  - pip
  - pip:
    - webdriver_manager